### ISSUE TITLE
shouldCrawl doesnt call onAllFinished

### ISSUE THREAD

**Issue by bymaximus** [antivanov/js-crawler#30]
When returning false to avoid crawl last url (i think) it doest call onAllFinished

**Comment by antivanov** [comment]
I will take a look and try to reproduce the issue.

**Comment by dtaylor7** [comment]
👍

**Comment by antivanov** [comment]
A couple of e2e tests for `shouldCrawl` were added. One of them failed, most likely because of the same bug described in this issue: when all the urls in the active crawler queue should not be crawled according to `shouldCrawl`, then the crawler would not call `onAllFinished`. This issue has been fixed https://github.com/antivanov/js-crawler/commit/bcd98cabfdf28581737e9c6fda59d92e0144ffd5 in the latest version and published to NPM.

Please, re-open the issue if it is still reproducible after the recent fix and, please, provide more details if possible.
